### ISSUE TITLE
Ortografía y Gramática.

### ISSUE THREAD

**Issue by AlexisRuiz00** [vrsanchez99/choose-your-own-adventure#6]
En la segunda línea del readme has escrito que se levanta  las 11pm, en lugar de 11am. Más adelante cuando bill se quita las botellas de alohol de encima, te falta la preposición "de".
Aparte de esto no estarían de más algunas cómas y signos de puntuación que faciliten la lectura.

**Comment by vrsanchez99** [comment]
Muchas gracias por su comentario. Intentaremos solucionar los errores lo más rápido posible.
